#! /bin/sh

#export TERM="xterm-256color"
#export LSCOLORS=exfxcxdxbxegedabagacad
#export CLICOLOR=1
#export LSCOLORS=gxfxcxexbxegedabaggCgd

alias vi='vim'
alias o='open' 

alias ls='ls --color=auto -F'
alias l1='clear; ls -1'
alias ll='ls -ihlt'
alias la='ls -A'
alias lc='clear ; ls'
alias llc='clear ; ll'
alias l='ls -CF'
alias lr='ls -RFlA | more'

alias poweroff='sudo poweroff'
alias reboot='sudo reboot'

alias cp='cp -R'
alias ps='ps -e'
alias cl='clear'

alias pip="pip-2.7"
alias py='python'
#alias ipy='ipython qtconsole --pylab=inline &>/dev/null'
alias ipy='ipython qtconsole --pylab=inline '
alias ipython='ipython --TerminalInteractiveShell.colors="Linux" --TerminalInteractiveShell.confirm_exit=False --TerminalInteractiveShell.deep_reload=True --pprint --TerminalInteractiveShell.banner1="" --nosep'
alias cd....='cd ../../../..'
alias cd...='cd ../../..'
alias cd..='cd ../..'
alias cd.='cd ..'
alias xat='cat'
alias cta='cat'
alias greo='grep'

