#! /bin/sh

#export TERM="xterm-256color"
#export LSCOLORS=exfxcxdxbxegedabagacad
export CLICOLOR=1
export LSCOLORS=gxfxcxexbxegedabaggCgd
export PATH=/usr/local/share/python:~/.bin:/usr/local/bin:$PATH
export PATH=~/.bin:$PATH
export PATH=~/.work/py:~/.work:$PATH

export HOST='remote'

#   export CC="gcc-4.2"
#   export CXX="g++-4.2"
#   export FFLAGS="-ff2c"

#export CXX=/usr/bin/g++-4.2
#export CC=/usr/bin/gcc-4.2
#export CPP=/usr/bin/cpp-4.2
#export LD=/usr/bin/ld

export PYTHONPATH=/usr/local/lib/python:$PYTHONPATH
export PYTHONSTARTUP=~/.pythonrc
# export DYLD_LIBRARY_PATH=/usr/local/Cellar/icu4c/4.8.1/include 




